export enum ErrorCode {
  // Global
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING',
  TENANT_DOCUMENT_ALREADY_EXISTS = 'TENANT_DOCUMENT_ALREADY_EXISTS',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_LAST_ADMIN = 'USER_LAST_ADMIN',

  // Sample
  SAMPLE_NOT_FOUND = 'SAMPLE_NOT_FOUND',

  // TODO: Add project-specific error codes with module prefix
}
