export enum ErrorCode {
  // Global
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Auth
  AUTH_INSUFFICIENT_ROLE = 'AUTH_INSUFFICIENT_ROLE',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_NO_SESSION = 'AUTH_NO_SESSION',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_CONTEXT_MISSING = 'TENANT_CONTEXT_MISSING',
  TENANT_DOCUMENT_ALREADY_EXISTS = 'TENANT_DOCUMENT_ALREADY_EXISTS',
  TENANT_REQUIRED = 'TENANT_REQUIRED',
  TENANT_INACTIVE = 'TENANT_INACTIVE',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS = 'USER_EMAIL_ALREADY_EXISTS',
  USER_LAST_ADMIN = 'USER_LAST_ADMIN',
  USER_INACTIVE = 'USER_INACTIVE',
  USER_CANNOT_DEACTIVATE_SELF = 'USER_CANNOT_DEACTIVATE_SELF',
  USER_CANNOT_CHANGE_OWN_ROLE = 'USER_CANNOT_CHANGE_OWN_ROLE',

  // Storage
  STORAGE_UPLOAD_FAILED = 'STORAGE_UPLOAD_FAILED',
  STORAGE_FILE_NOT_FOUND = 'STORAGE_FILE_NOT_FOUND',
  STORAGE_INVALID_KEY = 'STORAGE_INVALID_KEY',

  // Sample
  SAMPLE_NOT_FOUND = 'SAMPLE_NOT_FOUND',

  // TODO: Add project-specific error codes with module prefix
}
